// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/confmap/confmaptest"
)

func TestMetricsBuilderConfig(t *testing.T) {
	tests := []struct {
		name string
		want MetricsBuilderConfig
	}{
		{
			name: "default",
			want: DefaultMetricsBuilderConfig(),
		},
		{
			name: "all_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					MongodbatlasDbCounts: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"object_type"},
					},
					MongodbatlasDbSize: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"object_type"},
					},
					MongodbatlasDiskPartitionIopsAverage: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"disk_direction"},
					},
					MongodbatlasDiskPartitionIopsMax: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"disk_direction"},
					},
					MongodbatlasDiskPartitionLatencyAverage: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"disk_direction"},
					},
					MongodbatlasDiskPartitionLatencyMax: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"disk_direction"},
					},
					MongodbatlasDiskPartitionQueueDepth: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{},
					},
					MongodbatlasDiskPartitionSpaceAverage: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"disk_status"},
					},
					MongodbatlasDiskPartitionSpaceMax: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"disk_status"},
					},
					MongodbatlasDiskPartitionThroughput: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"disk_direction"},
					},
					MongodbatlasDiskPartitionUsageAverage: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"disk_status"},
					},
					MongodbatlasDiskPartitionUsageMax: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"disk_status"},
					},
					MongodbatlasDiskPartitionUtilizationAverage: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{},
					},
					MongodbatlasDiskPartitionUtilizationMax: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{},
					},
					MongodbatlasProcessAsserts: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"assert_type"},
					},
					MongodbatlasProcessBackgroundFlush: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{},
					},
					MongodbatlasProcessCacheIo: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"cache_direction"},
					},
					MongodbatlasProcessCacheRatio: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"cache_ratio_type"},
					},
					MongodbatlasProcessCacheSize: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{"cache_status"},
					},
					MongodbatlasProcessConnections: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					MongodbatlasProcessCPUChildrenNormalizedUsageAverage: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"cpu_state"},
					},
					MongodbatlasProcessCPUChildrenNormalizedUsageMax: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"cpu_state"},
					},
					MongodbatlasProcessCPUChildrenUsageAverage: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"cpu_state"},
					},
					MongodbatlasProcessCPUChildrenUsageMax: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"cpu_state"},
					},
					MongodbatlasProcessCPUNormalizedUsageAverage: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"cpu_state"},
					},
					MongodbatlasProcessCPUNormalizedUsageMax: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"cpu_state"},
					},
					MongodbatlasProcessCPUUsageAverage: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"cpu_state"},
					},
					MongodbatlasProcessCPUUsageMax: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"cpu_state"},
					},
					MongodbatlasProcessCursors: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"cursor_state"},
					},
					MongodbatlasProcessDbDocumentRate: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"document_status"},
					},
					MongodbatlasProcessDbOperationsRate: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"operation", "cluster_role"},
					},
					MongodbatlasProcessDbOperationsTime: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{"execution_type"},
					},
					MongodbatlasProcessDbQueryExecutorScanned: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"scanned_type"},
					},
					MongodbatlasProcessDbQueryTargetingScannedPerReturned: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"scanned_type"},
					},
					MongodbatlasProcessDbStorage: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"storage_status"},
					},
					MongodbatlasProcessGlobalLock: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"global_lock_state"},
					},
					MongodbatlasProcessIndexBtreeMissRatio: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{},
					},
					MongodbatlasProcessIndexCounters: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"btree_counter_type"},
					},
					MongodbatlasProcessJournalingCommits: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{},
					},
					MongodbatlasProcessJournalingDataFiles: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{},
					},
					MongodbatlasProcessJournalingWritten: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{},
					},
					MongodbatlasProcessMemoryUsage: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"memory_state"},
					},
					MongodbatlasProcessNetworkIo: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"direction"},
					},
					MongodbatlasProcessNetworkRequests: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					MongodbatlasProcessOplogRate: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{},
					},
					MongodbatlasProcessOplogTime: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"oplog_type"},
					},
					MongodbatlasProcessPageFaults: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"memory_issue_type"},
					},
					MongodbatlasProcessRestarts: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{},
					},
					MongodbatlasProcessTickets: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"ticket_type"},
					},
					MongodbatlasSystemCPUNormalizedUsageAverage: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"cpu_state"},
					},
					MongodbatlasSystemCPUNormalizedUsageMax: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"cpu_state"},
					},
					MongodbatlasSystemCPUUsageAverage: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"cpu_state"},
					},
					MongodbatlasSystemCPUUsageMax: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"cpu_state"},
					},
					MongodbatlasSystemFtsCPUNormalizedUsage: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"cpu_state"},
					},
					MongodbatlasSystemFtsCPUUsage: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"cpu_state"},
					},
					MongodbatlasSystemFtsDiskUsed: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{},
					},
					MongodbatlasSystemFtsMemoryUsage: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{"memory_state"},
					},
					MongodbatlasSystemMemoryUsageAverage: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"memory_status"},
					},
					MongodbatlasSystemMemoryUsageMax: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"memory_status"},
					},
					MongodbatlasSystemNetworkIoAverage: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"direction"},
					},
					MongodbatlasSystemNetworkIoMax: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"direction"},
					},
					MongodbatlasSystemPagingIoAverage: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"direction"},
					},
					MongodbatlasSystemPagingIoMax: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"direction"},
					},
					MongodbatlasSystemPagingUsageAverage: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"memory_state"},
					},
					MongodbatlasSystemPagingUsageMax: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"memory_state"},
					},
				},
				ResourceAttributes: ResourceAttributesConfig{
					MongodbAtlasClusterName:     ResourceAttributeConfig{Enabled: true},
					MongodbAtlasDbName:          ResourceAttributeConfig{Enabled: true},
					MongodbAtlasDiskPartition:   ResourceAttributeConfig{Enabled: true},
					MongodbAtlasHostName:        ResourceAttributeConfig{Enabled: true},
					MongodbAtlasOrgName:         ResourceAttributeConfig{Enabled: true},
					MongodbAtlasProcessID:       ResourceAttributeConfig{Enabled: true},
					MongodbAtlasProcessPort:     ResourceAttributeConfig{Enabled: true},
					MongodbAtlasProcessTypeName: ResourceAttributeConfig{Enabled: true},
					MongodbAtlasProjectID:       ResourceAttributeConfig{Enabled: true},
					MongodbAtlasProjectName:     ResourceAttributeConfig{Enabled: true},
					MongodbAtlasProviderName:    ResourceAttributeConfig{Enabled: true},
					MongodbAtlasRegionName:      ResourceAttributeConfig{Enabled: true},
					MongodbAtlasUserAlias:       ResourceAttributeConfig{Enabled: true},
				},
			},
		},
		{
			name: "none_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					MongodbatlasDbCounts: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"object_type"},
					},
					MongodbatlasDbSize: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"object_type"},
					},
					MongodbatlasDiskPartitionIopsAverage: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"disk_direction"},
					},
					MongodbatlasDiskPartitionIopsMax: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"disk_direction"},
					},
					MongodbatlasDiskPartitionLatencyAverage: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"disk_direction"},
					},
					MongodbatlasDiskPartitionLatencyMax: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"disk_direction"},
					},
					MongodbatlasDiskPartitionQueueDepth: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{},
					},
					MongodbatlasDiskPartitionSpaceAverage: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"disk_status"},
					},
					MongodbatlasDiskPartitionSpaceMax: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"disk_status"},
					},
					MongodbatlasDiskPartitionThroughput: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"disk_direction"},
					},
					MongodbatlasDiskPartitionUsageAverage: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"disk_status"},
					},
					MongodbatlasDiskPartitionUsageMax: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"disk_status"},
					},
					MongodbatlasDiskPartitionUtilizationAverage: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{},
					},
					MongodbatlasDiskPartitionUtilizationMax: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{},
					},
					MongodbatlasProcessAsserts: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"assert_type"},
					},
					MongodbatlasProcessBackgroundFlush: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{},
					},
					MongodbatlasProcessCacheIo: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"cache_direction"},
					},
					MongodbatlasProcessCacheRatio: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"cache_ratio_type"},
					},
					MongodbatlasProcessCacheSize: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{"cache_status"},
					},
					MongodbatlasProcessConnections: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					MongodbatlasProcessCPUChildrenNormalizedUsageAverage: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"cpu_state"},
					},
					MongodbatlasProcessCPUChildrenNormalizedUsageMax: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"cpu_state"},
					},
					MongodbatlasProcessCPUChildrenUsageAverage: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"cpu_state"},
					},
					MongodbatlasProcessCPUChildrenUsageMax: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"cpu_state"},
					},
					MongodbatlasProcessCPUNormalizedUsageAverage: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"cpu_state"},
					},
					MongodbatlasProcessCPUNormalizedUsageMax: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"cpu_state"},
					},
					MongodbatlasProcessCPUUsageAverage: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"cpu_state"},
					},
					MongodbatlasProcessCPUUsageMax: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"cpu_state"},
					},
					MongodbatlasProcessCursors: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"cursor_state"},
					},
					MongodbatlasProcessDbDocumentRate: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"document_status"},
					},
					MongodbatlasProcessDbOperationsRate: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"operation", "cluster_role"},
					},
					MongodbatlasProcessDbOperationsTime: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{"execution_type"},
					},
					MongodbatlasProcessDbQueryExecutorScanned: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"scanned_type"},
					},
					MongodbatlasProcessDbQueryTargetingScannedPerReturned: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"scanned_type"},
					},
					MongodbatlasProcessDbStorage: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"storage_status"},
					},
					MongodbatlasProcessGlobalLock: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"global_lock_state"},
					},
					MongodbatlasProcessIndexBtreeMissRatio: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{},
					},
					MongodbatlasProcessIndexCounters: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"btree_counter_type"},
					},
					MongodbatlasProcessJournalingCommits: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{},
					},
					MongodbatlasProcessJournalingDataFiles: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{},
					},
					MongodbatlasProcessJournalingWritten: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{},
					},
					MongodbatlasProcessMemoryUsage: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"memory_state"},
					},
					MongodbatlasProcessNetworkIo: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"direction"},
					},
					MongodbatlasProcessNetworkRequests: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					MongodbatlasProcessOplogRate: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{},
					},
					MongodbatlasProcessOplogTime: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"oplog_type"},
					},
					MongodbatlasProcessPageFaults: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"memory_issue_type"},
					},
					MongodbatlasProcessRestarts: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{},
					},
					MongodbatlasProcessTickets: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"ticket_type"},
					},
					MongodbatlasSystemCPUNormalizedUsageAverage: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"cpu_state"},
					},
					MongodbatlasSystemCPUNormalizedUsageMax: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"cpu_state"},
					},
					MongodbatlasSystemCPUUsageAverage: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"cpu_state"},
					},
					MongodbatlasSystemCPUUsageMax: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"cpu_state"},
					},
					MongodbatlasSystemFtsCPUNormalizedUsage: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"cpu_state"},
					},
					MongodbatlasSystemFtsCPUUsage: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"cpu_state"},
					},
					MongodbatlasSystemFtsDiskUsed: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{},
					},
					MongodbatlasSystemFtsMemoryUsage: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{"memory_state"},
					},
					MongodbatlasSystemMemoryUsageAverage: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"memory_status"},
					},
					MongodbatlasSystemMemoryUsageMax: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"memory_status"},
					},
					MongodbatlasSystemNetworkIoAverage: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"direction"},
					},
					MongodbatlasSystemNetworkIoMax: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"direction"},
					},
					MongodbatlasSystemPagingIoAverage: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"direction"},
					},
					MongodbatlasSystemPagingIoMax: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"direction"},
					},
					MongodbatlasSystemPagingUsageAverage: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"memory_state"},
					},
					MongodbatlasSystemPagingUsageMax: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{"memory_state"},
					},
				},
				ResourceAttributes: ResourceAttributesConfig{
					MongodbAtlasClusterName:     ResourceAttributeConfig{Enabled: false},
					MongodbAtlasDbName:          ResourceAttributeConfig{Enabled: false},
					MongodbAtlasDiskPartition:   ResourceAttributeConfig{Enabled: false},
					MongodbAtlasHostName:        ResourceAttributeConfig{Enabled: false},
					MongodbAtlasOrgName:         ResourceAttributeConfig{Enabled: false},
					MongodbAtlasProcessID:       ResourceAttributeConfig{Enabled: false},
					MongodbAtlasProcessPort:     ResourceAttributeConfig{Enabled: false},
					MongodbAtlasProcessTypeName: ResourceAttributeConfig{Enabled: false},
					MongodbAtlasProjectID:       ResourceAttributeConfig{Enabled: false},
					MongodbAtlasProjectName:     ResourceAttributeConfig{Enabled: false},
					MongodbAtlasProviderName:    ResourceAttributeConfig{Enabled: false},
					MongodbAtlasRegionName:      ResourceAttributeConfig{Enabled: false},
					MongodbAtlasUserAlias:       ResourceAttributeConfig{Enabled: false},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadMetricsBuilderConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(MetricConfig{}, ResourceAttributeConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func loadMetricsBuilderConfig(t *testing.T, name string) MetricsBuilderConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	cfg := DefaultMetricsBuilderConfig()
	require.NoError(t, sub.Unmarshal(&cfg, confmap.WithIgnoreUnused()))
	return cfg
}

func TestResourceAttributesConfig(t *testing.T) {
	tests := []struct {
		name string
		want ResourceAttributesConfig
	}{
		{
			name: "default",
			want: DefaultResourceAttributesConfig(),
		},
		{
			name: "all_set",
			want: ResourceAttributesConfig{
				MongodbAtlasClusterName:     ResourceAttributeConfig{Enabled: true},
				MongodbAtlasDbName:          ResourceAttributeConfig{Enabled: true},
				MongodbAtlasDiskPartition:   ResourceAttributeConfig{Enabled: true},
				MongodbAtlasHostName:        ResourceAttributeConfig{Enabled: true},
				MongodbAtlasOrgName:         ResourceAttributeConfig{Enabled: true},
				MongodbAtlasProcessID:       ResourceAttributeConfig{Enabled: true},
				MongodbAtlasProcessPort:     ResourceAttributeConfig{Enabled: true},
				MongodbAtlasProcessTypeName: ResourceAttributeConfig{Enabled: true},
				MongodbAtlasProjectID:       ResourceAttributeConfig{Enabled: true},
				MongodbAtlasProjectName:     ResourceAttributeConfig{Enabled: true},
				MongodbAtlasProviderName:    ResourceAttributeConfig{Enabled: true},
				MongodbAtlasRegionName:      ResourceAttributeConfig{Enabled: true},
				MongodbAtlasUserAlias:       ResourceAttributeConfig{Enabled: true},
			},
		},
		{
			name: "none_set",
			want: ResourceAttributesConfig{
				MongodbAtlasClusterName:     ResourceAttributeConfig{Enabled: false},
				MongodbAtlasDbName:          ResourceAttributeConfig{Enabled: false},
				MongodbAtlasDiskPartition:   ResourceAttributeConfig{Enabled: false},
				MongodbAtlasHostName:        ResourceAttributeConfig{Enabled: false},
				MongodbAtlasOrgName:         ResourceAttributeConfig{Enabled: false},
				MongodbAtlasProcessID:       ResourceAttributeConfig{Enabled: false},
				MongodbAtlasProcessPort:     ResourceAttributeConfig{Enabled: false},
				MongodbAtlasProcessTypeName: ResourceAttributeConfig{Enabled: false},
				MongodbAtlasProjectID:       ResourceAttributeConfig{Enabled: false},
				MongodbAtlasProjectName:     ResourceAttributeConfig{Enabled: false},
				MongodbAtlasProviderName:    ResourceAttributeConfig{Enabled: false},
				MongodbAtlasRegionName:      ResourceAttributeConfig{Enabled: false},
				MongodbAtlasUserAlias:       ResourceAttributeConfig{Enabled: false},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadResourceAttributesConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(ResourceAttributeConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func loadResourceAttributesConfig(t *testing.T, name string) ResourceAttributesConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	sub, err = sub.Sub("resource_attributes")
	require.NoError(t, err)
	cfg := DefaultResourceAttributesConfig()
	require.NoError(t, sub.Unmarshal(&cfg))
	return cfg
}
