// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"fmt"
	"slices"

	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/filter"
)

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string   `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []string `mapstructure:"attributes"`
	definedAttributes   []string
	requiredAttributes  []string
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}
	for _, val := range ms.EnabledAttributes {
		if !slices.Contains(ms.definedAttributes, val) {
			return fmt.Errorf("%v is not defined in metadata.yaml", val)
		}
	}

	for _, val := range ms.requiredAttributes {
		if !slices.Contains(ms.EnabledAttributes, val) {
			return fmt.Errorf("`attributes` field must contain required attribute: %v", val)
		}
	}

	if ms.AggregationStrategy != AggregationStrategySum &&
		ms.AggregationStrategy != AggregationStrategyAvg &&
		ms.AggregationStrategy != AggregationStrategyMin &&
		ms.AggregationStrategy != AggregationStrategyMax {
		return fmt.Errorf("invalid aggregation strategy set: '%v'", ms.AggregationStrategy)
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// AttributeConfig holds configuration information for a particular metric.
type AttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`
}

// MetricsConfig provides config for mongodb_atlas metrics.
type MetricsConfig struct {
	MongodbatlasDbCounts                                  MetricConfig `mapstructure:"mongodbatlas.db.counts"`
	MongodbatlasDbSize                                    MetricConfig `mapstructure:"mongodbatlas.db.size"`
	MongodbatlasDiskPartitionIopsAverage                  MetricConfig `mapstructure:"mongodbatlas.disk.partition.iops.average"`
	MongodbatlasDiskPartitionIopsMax                      MetricConfig `mapstructure:"mongodbatlas.disk.partition.iops.max"`
	MongodbatlasDiskPartitionLatencyAverage               MetricConfig `mapstructure:"mongodbatlas.disk.partition.latency.average"`
	MongodbatlasDiskPartitionLatencyMax                   MetricConfig `mapstructure:"mongodbatlas.disk.partition.latency.max"`
	MongodbatlasDiskPartitionQueueDepth                   MetricConfig `mapstructure:"mongodbatlas.disk.partition.queue.depth"`
	MongodbatlasDiskPartitionSpaceAverage                 MetricConfig `mapstructure:"mongodbatlas.disk.partition.space.average"`
	MongodbatlasDiskPartitionSpaceMax                     MetricConfig `mapstructure:"mongodbatlas.disk.partition.space.max"`
	MongodbatlasDiskPartitionThroughput                   MetricConfig `mapstructure:"mongodbatlas.disk.partition.throughput"`
	MongodbatlasDiskPartitionUsageAverage                 MetricConfig `mapstructure:"mongodbatlas.disk.partition.usage.average"`
	MongodbatlasDiskPartitionUsageMax                     MetricConfig `mapstructure:"mongodbatlas.disk.partition.usage.max"`
	MongodbatlasDiskPartitionUtilizationAverage           MetricConfig `mapstructure:"mongodbatlas.disk.partition.utilization.average"`
	MongodbatlasDiskPartitionUtilizationMax               MetricConfig `mapstructure:"mongodbatlas.disk.partition.utilization.max"`
	MongodbatlasProcessAsserts                            MetricConfig `mapstructure:"mongodbatlas.process.asserts"`
	MongodbatlasProcessBackgroundFlush                    MetricConfig `mapstructure:"mongodbatlas.process.background_flush"`
	MongodbatlasProcessCacheIo                            MetricConfig `mapstructure:"mongodbatlas.process.cache.io"`
	MongodbatlasProcessCacheRatio                         MetricConfig `mapstructure:"mongodbatlas.process.cache.ratio"`
	MongodbatlasProcessCacheSize                          MetricConfig `mapstructure:"mongodbatlas.process.cache.size"`
	MongodbatlasProcessConnections                        MetricConfig `mapstructure:"mongodbatlas.process.connections"`
	MongodbatlasProcessCPUChildrenNormalizedUsageAverage  MetricConfig `mapstructure:"mongodbatlas.process.cpu.children.normalized.usage.average"`
	MongodbatlasProcessCPUChildrenNormalizedUsageMax      MetricConfig `mapstructure:"mongodbatlas.process.cpu.children.normalized.usage.max"`
	MongodbatlasProcessCPUChildrenUsageAverage            MetricConfig `mapstructure:"mongodbatlas.process.cpu.children.usage.average"`
	MongodbatlasProcessCPUChildrenUsageMax                MetricConfig `mapstructure:"mongodbatlas.process.cpu.children.usage.max"`
	MongodbatlasProcessCPUNormalizedUsageAverage          MetricConfig `mapstructure:"mongodbatlas.process.cpu.normalized.usage.average"`
	MongodbatlasProcessCPUNormalizedUsageMax              MetricConfig `mapstructure:"mongodbatlas.process.cpu.normalized.usage.max"`
	MongodbatlasProcessCPUUsageAverage                    MetricConfig `mapstructure:"mongodbatlas.process.cpu.usage.average"`
	MongodbatlasProcessCPUUsageMax                        MetricConfig `mapstructure:"mongodbatlas.process.cpu.usage.max"`
	MongodbatlasProcessCursors                            MetricConfig `mapstructure:"mongodbatlas.process.cursors"`
	MongodbatlasProcessDbDocumentRate                     MetricConfig `mapstructure:"mongodbatlas.process.db.document.rate"`
	MongodbatlasProcessDbOperationsRate                   MetricConfig `mapstructure:"mongodbatlas.process.db.operations.rate"`
	MongodbatlasProcessDbOperationsTime                   MetricConfig `mapstructure:"mongodbatlas.process.db.operations.time"`
	MongodbatlasProcessDbQueryExecutorScanned             MetricConfig `mapstructure:"mongodbatlas.process.db.query_executor.scanned"`
	MongodbatlasProcessDbQueryTargetingScannedPerReturned MetricConfig `mapstructure:"mongodbatlas.process.db.query_targeting.scanned_per_returned"`
	MongodbatlasProcessDbStorage                          MetricConfig `mapstructure:"mongodbatlas.process.db.storage"`
	MongodbatlasProcessGlobalLock                         MetricConfig `mapstructure:"mongodbatlas.process.global_lock"`
	MongodbatlasProcessIndexBtreeMissRatio                MetricConfig `mapstructure:"mongodbatlas.process.index.btree_miss_ratio"`
	MongodbatlasProcessIndexCounters                      MetricConfig `mapstructure:"mongodbatlas.process.index.counters"`
	MongodbatlasProcessJournalingCommits                  MetricConfig `mapstructure:"mongodbatlas.process.journaling.commits"`
	MongodbatlasProcessJournalingDataFiles                MetricConfig `mapstructure:"mongodbatlas.process.journaling.data_files"`
	MongodbatlasProcessJournalingWritten                  MetricConfig `mapstructure:"mongodbatlas.process.journaling.written"`
	MongodbatlasProcessMemoryUsage                        MetricConfig `mapstructure:"mongodbatlas.process.memory.usage"`
	MongodbatlasProcessNetworkIo                          MetricConfig `mapstructure:"mongodbatlas.process.network.io"`
	MongodbatlasProcessNetworkRequests                    MetricConfig `mapstructure:"mongodbatlas.process.network.requests"`
	MongodbatlasProcessOplogRate                          MetricConfig `mapstructure:"mongodbatlas.process.oplog.rate"`
	MongodbatlasProcessOplogTime                          MetricConfig `mapstructure:"mongodbatlas.process.oplog.time"`
	MongodbatlasProcessPageFaults                         MetricConfig `mapstructure:"mongodbatlas.process.page_faults"`
	MongodbatlasProcessRestarts                           MetricConfig `mapstructure:"mongodbatlas.process.restarts"`
	MongodbatlasProcessTickets                            MetricConfig `mapstructure:"mongodbatlas.process.tickets"`
	MongodbatlasSystemCPUNormalizedUsageAverage           MetricConfig `mapstructure:"mongodbatlas.system.cpu.normalized.usage.average"`
	MongodbatlasSystemCPUNormalizedUsageMax               MetricConfig `mapstructure:"mongodbatlas.system.cpu.normalized.usage.max"`
	MongodbatlasSystemCPUUsageAverage                     MetricConfig `mapstructure:"mongodbatlas.system.cpu.usage.average"`
	MongodbatlasSystemCPUUsageMax                         MetricConfig `mapstructure:"mongodbatlas.system.cpu.usage.max"`
	MongodbatlasSystemFtsCPUNormalizedUsage               MetricConfig `mapstructure:"mongodbatlas.system.fts.cpu.normalized.usage"`
	MongodbatlasSystemFtsCPUUsage                         MetricConfig `mapstructure:"mongodbatlas.system.fts.cpu.usage"`
	MongodbatlasSystemFtsDiskUsed                         MetricConfig `mapstructure:"mongodbatlas.system.fts.disk.used"`
	MongodbatlasSystemFtsMemoryUsage                      MetricConfig `mapstructure:"mongodbatlas.system.fts.memory.usage"`
	MongodbatlasSystemMemoryUsageAverage                  MetricConfig `mapstructure:"mongodbatlas.system.memory.usage.average"`
	MongodbatlasSystemMemoryUsageMax                      MetricConfig `mapstructure:"mongodbatlas.system.memory.usage.max"`
	MongodbatlasSystemNetworkIoAverage                    MetricConfig `mapstructure:"mongodbatlas.system.network.io.average"`
	MongodbatlasSystemNetworkIoMax                        MetricConfig `mapstructure:"mongodbatlas.system.network.io.max"`
	MongodbatlasSystemPagingIoAverage                     MetricConfig `mapstructure:"mongodbatlas.system.paging.io.average"`
	MongodbatlasSystemPagingIoMax                         MetricConfig `mapstructure:"mongodbatlas.system.paging.io.max"`
	MongodbatlasSystemPagingUsageAverage                  MetricConfig `mapstructure:"mongodbatlas.system.paging.usage.average"`
	MongodbatlasSystemPagingUsageMax                      MetricConfig `mapstructure:"mongodbatlas.system.paging.usage.max"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		MongodbatlasDbCounts: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"object_type"},
			EnabledAttributes:   []string{},
		},
		MongodbatlasDbSize: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"object_type"},
			EnabledAttributes:   []string{},
		},
		MongodbatlasDiskPartitionIopsAverage: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"disk_direction"},
			EnabledAttributes:   []string{},
		},
		MongodbatlasDiskPartitionIopsMax: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"disk_direction"},
			EnabledAttributes:   []string{},
		},
		MongodbatlasDiskPartitionLatencyAverage: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"disk_direction"},
			EnabledAttributes:   []string{},
		},
		MongodbatlasDiskPartitionLatencyMax: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"disk_direction"},
			EnabledAttributes:   []string{},
		},
		MongodbatlasDiskPartitionQueueDepth: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		MongodbatlasDiskPartitionSpaceAverage: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"disk_status"},
			EnabledAttributes:   []string{"disk_status"},
		},
		MongodbatlasDiskPartitionSpaceMax: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"disk_status"},
			EnabledAttributes:   []string{"disk_status"},
		},
		MongodbatlasDiskPartitionThroughput: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"disk_direction"},
			EnabledAttributes:   []string{},
		},
		MongodbatlasDiskPartitionUsageAverage: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"disk_status"},
			EnabledAttributes:   []string{"disk_status"},
		},
		MongodbatlasDiskPartitionUsageMax: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"disk_status"},
			EnabledAttributes:   []string{"disk_status"},
		},
		MongodbatlasDiskPartitionUtilizationAverage: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		MongodbatlasDiskPartitionUtilizationMax: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		MongodbatlasProcessAsserts: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"assert_type"},
			EnabledAttributes:   []string{"assert_type"},
		},
		MongodbatlasProcessBackgroundFlush: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		MongodbatlasProcessCacheIo: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"cache_direction"},
			EnabledAttributes:   []string{"cache_direction"},
		},
		MongodbatlasProcessCacheRatio: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"cache_ratio_type"},
			EnabledAttributes:   []string{},
		},
		MongodbatlasProcessCacheSize: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"cache_status"},
			EnabledAttributes:   []string{"cache_status"},
		},
		MongodbatlasProcessConnections: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		MongodbatlasProcessCPUChildrenNormalizedUsageAverage: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"cpu_state"},
			EnabledAttributes:   []string{"cpu_state"},
		},
		MongodbatlasProcessCPUChildrenNormalizedUsageMax: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"cpu_state"},
			EnabledAttributes:   []string{"cpu_state"},
		},
		MongodbatlasProcessCPUChildrenUsageAverage: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"cpu_state"},
			EnabledAttributes:   []string{"cpu_state"},
		},
		MongodbatlasProcessCPUChildrenUsageMax: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"cpu_state"},
			EnabledAttributes:   []string{"cpu_state"},
		},
		MongodbatlasProcessCPUNormalizedUsageAverage: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"cpu_state"},
			EnabledAttributes:   []string{"cpu_state"},
		},
		MongodbatlasProcessCPUNormalizedUsageMax: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"cpu_state"},
			EnabledAttributes:   []string{"cpu_state"},
		},
		MongodbatlasProcessCPUUsageAverage: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"cpu_state"},
			EnabledAttributes:   []string{"cpu_state"},
		},
		MongodbatlasProcessCPUUsageMax: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"cpu_state"},
			EnabledAttributes:   []string{"cpu_state"},
		},
		MongodbatlasProcessCursors: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"cursor_state"},
			EnabledAttributes:   []string{"cursor_state"},
		},
		MongodbatlasProcessDbDocumentRate: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"document_status"},
			EnabledAttributes:   []string{"document_status"},
		},
		MongodbatlasProcessDbOperationsRate: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"operation", "cluster_role"},
			EnabledAttributes:   []string{"operation", "cluster_role"},
		},
		MongodbatlasProcessDbOperationsTime: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"execution_type"},
			EnabledAttributes:   []string{"execution_type"},
		},
		MongodbatlasProcessDbQueryExecutorScanned: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"scanned_type"},
			EnabledAttributes:   []string{},
		},
		MongodbatlasProcessDbQueryTargetingScannedPerReturned: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"scanned_type"},
			EnabledAttributes:   []string{},
		},
		MongodbatlasProcessDbStorage: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"storage_status"},
			EnabledAttributes:   []string{},
		},
		MongodbatlasProcessGlobalLock: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"global_lock_state"},
			EnabledAttributes:   []string{},
		},
		MongodbatlasProcessIndexBtreeMissRatio: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		MongodbatlasProcessIndexCounters: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"btree_counter_type"},
			EnabledAttributes:   []string{},
		},
		MongodbatlasProcessJournalingCommits: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		MongodbatlasProcessJournalingDataFiles: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		MongodbatlasProcessJournalingWritten: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		MongodbatlasProcessMemoryUsage: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"memory_state"},
			EnabledAttributes:   []string{},
		},
		MongodbatlasProcessNetworkIo: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"direction"},
			EnabledAttributes:   []string{"direction"},
		},
		MongodbatlasProcessNetworkRequests: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		MongodbatlasProcessOplogRate: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		MongodbatlasProcessOplogTime: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"oplog_type"},
			EnabledAttributes:   []string{},
		},
		MongodbatlasProcessPageFaults: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"memory_issue_type"},
			EnabledAttributes:   []string{"memory_issue_type"},
		},
		MongodbatlasProcessRestarts: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		MongodbatlasProcessTickets: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"ticket_type"},
			EnabledAttributes:   []string{"ticket_type"},
		},
		MongodbatlasSystemCPUNormalizedUsageAverage: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"cpu_state"},
			EnabledAttributes:   []string{"cpu_state"},
		},
		MongodbatlasSystemCPUNormalizedUsageMax: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"cpu_state"},
			EnabledAttributes:   []string{"cpu_state"},
		},
		MongodbatlasSystemCPUUsageAverage: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"cpu_state"},
			EnabledAttributes:   []string{"cpu_state"},
		},
		MongodbatlasSystemCPUUsageMax: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"cpu_state"},
			EnabledAttributes:   []string{"cpu_state"},
		},
		MongodbatlasSystemFtsCPUNormalizedUsage: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"cpu_state"},
			EnabledAttributes:   []string{"cpu_state"},
		},
		MongodbatlasSystemFtsCPUUsage: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"cpu_state"},
			EnabledAttributes:   []string{"cpu_state"},
		},
		MongodbatlasSystemFtsDiskUsed: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		MongodbatlasSystemFtsMemoryUsage: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"memory_state"},
			EnabledAttributes:   []string{},
		},
		MongodbatlasSystemMemoryUsageAverage: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"memory_status"},
			EnabledAttributes:   []string{},
		},
		MongodbatlasSystemMemoryUsageMax: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"memory_status"},
			EnabledAttributes:   []string{},
		},
		MongodbatlasSystemNetworkIoAverage: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"direction"},
			EnabledAttributes:   []string{"direction"},
		},
		MongodbatlasSystemNetworkIoMax: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"direction"},
			EnabledAttributes:   []string{"direction"},
		},
		MongodbatlasSystemPagingIoAverage: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"direction"},
			EnabledAttributes:   []string{"direction"},
		},
		MongodbatlasSystemPagingIoMax: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"direction"},
			EnabledAttributes:   []string{"direction"},
		},
		MongodbatlasSystemPagingUsageAverage: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"memory_state"},
			EnabledAttributes:   []string{},
		},
		MongodbatlasSystemPagingUsageMax: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"memory_state"},
			EnabledAttributes:   []string{},
		},
	}
}

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`
	// Experimental: MetricsInclude defines a list of filters for attribute values.
	// If the list is not empty, only metrics with matching resource attribute values will be emitted.
	MetricsInclude []filter.Config `mapstructure:"metrics_include"`
	// Experimental: MetricsExclude defines a list of filters for attribute values.
	// If the list is not empty, metrics with matching resource attribute values will not be emitted.
	// MetricsInclude has higher priority than MetricsExclude.
	MetricsExclude []filter.Config `mapstructure:"metrics_exclude"`

	enabledSetByUser bool
}

func (rac *ResourceAttributeConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(rac)
	if err != nil {
		return err
	}
	rac.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// ResourceAttributesConfig provides config for mongodb_atlas resource attributes.
type ResourceAttributesConfig struct {
	MongodbAtlasClusterName     ResourceAttributeConfig `mapstructure:"mongodb_atlas.cluster.name"`
	MongodbAtlasDbName          ResourceAttributeConfig `mapstructure:"mongodb_atlas.db.name"`
	MongodbAtlasDiskPartition   ResourceAttributeConfig `mapstructure:"mongodb_atlas.disk.partition"`
	MongodbAtlasHostName        ResourceAttributeConfig `mapstructure:"mongodb_atlas.host.name"`
	MongodbAtlasOrgName         ResourceAttributeConfig `mapstructure:"mongodb_atlas.org_name"`
	MongodbAtlasProcessID       ResourceAttributeConfig `mapstructure:"mongodb_atlas.process.id"`
	MongodbAtlasProcessPort     ResourceAttributeConfig `mapstructure:"mongodb_atlas.process.port"`
	MongodbAtlasProcessTypeName ResourceAttributeConfig `mapstructure:"mongodb_atlas.process.type_name"`
	MongodbAtlasProjectID       ResourceAttributeConfig `mapstructure:"mongodb_atlas.project.id"`
	MongodbAtlasProjectName     ResourceAttributeConfig `mapstructure:"mongodb_atlas.project.name"`
	MongodbAtlasProviderName    ResourceAttributeConfig `mapstructure:"mongodb_atlas.provider.name"`
	MongodbAtlasRegionName      ResourceAttributeConfig `mapstructure:"mongodb_atlas.region.name"`
	MongodbAtlasUserAlias       ResourceAttributeConfig `mapstructure:"mongodb_atlas.user.alias"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	return ResourceAttributesConfig{
		MongodbAtlasClusterName: ResourceAttributeConfig{
			Enabled: false,
		},
		MongodbAtlasDbName: ResourceAttributeConfig{
			Enabled: true,
		},
		MongodbAtlasDiskPartition: ResourceAttributeConfig{
			Enabled: true,
		},
		MongodbAtlasHostName: ResourceAttributeConfig{
			Enabled: true,
		},
		MongodbAtlasOrgName: ResourceAttributeConfig{
			Enabled: true,
		},
		MongodbAtlasProcessID: ResourceAttributeConfig{
			Enabled: true,
		},
		MongodbAtlasProcessPort: ResourceAttributeConfig{
			Enabled: true,
		},
		MongodbAtlasProcessTypeName: ResourceAttributeConfig{
			Enabled: true,
		},
		MongodbAtlasProjectID: ResourceAttributeConfig{
			Enabled: true,
		},
		MongodbAtlasProjectName: ResourceAttributeConfig{
			Enabled: true,
		},
		MongodbAtlasProviderName: ResourceAttributeConfig{
			Enabled: false,
		},
		MongodbAtlasRegionName: ResourceAttributeConfig{
			Enabled: false,
		},
		MongodbAtlasUserAlias: ResourceAttributeConfig{
			Enabled: false,
		},
	}
}

// MetricsBuilderConfig is a configuration for mongodb_atlas metrics builder.
type MetricsBuilderConfig struct {
	Metrics            MetricsConfig            `mapstructure:"metrics"`
	ResourceAttributes ResourceAttributesConfig `mapstructure:"resource_attributes"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics:            DefaultMetricsConfig(),
		ResourceAttributes: DefaultResourceAttributesConfig(),
	}
}
